name: 🐞 Bug Report
description: Report a bug or an issue you've found with recce
title: "[Bug] <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks. 
        Tip: you can find the executed sql in `logs/dbt.log`
      render: shell
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
        - recce: 0.1.0 (`recce version`)
        - OS: MacOS 13.2.1
        - Python: 3.9.12 (`python3 --version`)
        - Data Warehouse: snowflake or postgresql 14.10
        - dbt: (`dbt --version`)

      value: |
        - recce:
        - OS:
        - Python:
        - Data Warehouse:
        - dbt:
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
